#define HEMISPHERE_AVAILABLE_APPLETS 4
#define HEMISPHERE_APPLETS { \
    DECLARE_APPLET(1, SampleAndHold), \
    DECLARE_APPLET(2, MinMax),\
    DECLARE_APPLET(5, SumDiff),\
	DECLARE_APPLET(3, Switch), \
	DECLARE_APPLET(4, Brancher), \
}
