#define HEMISPHERE_AVAILABLE_APPLETS 16
#define HEMISPHERE_APPLETS { \
    DECLARE_APPLET( 7, SkewedLFO), \
    DECLARE_APPLET( 8, ADSREG), \
    DECLARE_APPLET( 9, DualQuant), \
    DECLARE_APPLET( 6, ClockDivider), \
    DECLARE_APPLET(18, TM), \
    DECLARE_APPLET(14, Sequence5), \
    DECLARE_APPLET(15, TrigSeq), \
    DECLARE_APPLET(19, Slew), \
    DECLARE_APPLET( 1, SampleAndHold), \
    DECLARE_APPLET(12, Calculate),\
    DECLARE_APPLET(10, Logic), \
    DECLARE_APPLET(13, TLNeuron), \
    DECLARE_APPLET( 3, Switch), \
	DECLARE_APPLET( 4, Brancher), \
	DECLARE_APPLET(16, LoFiPCM), \
	DECLARE_APPLET(17, GatedVCA), \
}
